// UN Member States (193 countries) with ISO 3166-1 alpha-2 codes
export const UN_MEMBER_FLAGS = [
  { iso2: "af", country_name: "Afghanistan" },
  { iso2: "al", country_name: "Albania" },
  { iso2: "dz", country_name: "Algeria" },
  { iso2: "ad", country_name: "Andorra" },
  { iso2: "ao", country_name: "Angola" },
  { iso2: "ag", country_name: "Antigua and Barbuda" },
  { iso2: "ar", country_name: "Argentina" },
  { iso2: "am", country_name: "Armenia" },
  { iso2: "au", country_name: "Australia" },
  { iso2: "at", country_name: "Austria" },
  { iso2: "az", country_name: "Azerbaijan" },
  { iso2: "bs", country_name: "Bahamas" },
  { iso2: "bh", country_name: "Bahrain" },
  { iso2: "bd", country_name: "Bangladesh" },
  { iso2: "bb", country_name: "Barbados" },
  { iso2: "by", country_name: "Belarus" },
  { iso2: "be", country_name: "Belgium" },
  { iso2: "bz", country_name: "Belize" },
  { iso2: "bj", country_name: "Benin" },
  { iso2: "bt", country_name: "Bhutan" },
  { iso2: "bo", country_name: "Bolivia" },
  { iso2: "ba", country_name: "Bosnia and Herzegovina" },
  { iso2: "bw", country_name: "Botswana" },
  { iso2: "br", country_name: "Brazil" },
  { iso2: "bn", country_name: "Brunei" },
  { iso2: "bg", country_name: "Bulgaria" },
  { iso2: "bf", country_name: "Burkina Faso" },
  { iso2: "bi", country_name: "Burundi" },
  { iso2: "cv", country_name: "Cabo Verde" },
  { iso2: "kh", country_name: "Cambodia" },
  { iso2: "cm", country_name: "Cameroon" },
  { iso2: "ca", country_name: "Canada" },
  { iso2: "cf", country_name: "Central African Republic" },
  { iso2: "td", country_name: "Chad" },
  { iso2: "cl", country_name: "Chile" },
  { iso2: "cn", country_name: "China" },
  { iso2: "co", country_name: "Colombia" },
  { iso2: "km", country_name: "Comoros" },
  { iso2: "cg", country_name: "Congo" },
  { iso2: "cd", country_name: "Democratic Republic of the Congo" },
  { iso2: "cr", country_name: "Costa Rica" },
  { iso2: "ci", country_name: "Côte d'Ivoire" },
  { iso2: "hr", country_name: "Croatia" },
  { iso2: "cu", country_name: "Cuba" },
  { iso2: "cy", country_name: "Cyprus" },
  { iso2: "cz", country_name: "Czechia" },
  { iso2: "dk", country_name: "Denmark" },
  { iso2: "dj", country_name: "Djibouti" },
  { iso2: "dm", country_name: "Dominica" },
  { iso2: "do", country_name: "Dominican Republic" },
  { iso2: "ec", country_name: "Ecuador" },
  { iso2: "eg", country_name: "Egypt" },
  { iso2: "sv", country_name: "El Salvador" },
  { iso2: "gq", country_name: "Equatorial Guinea" },
  { iso2: "er", country_name: "Eritrea" },
  { iso2: "ee", country_name: "Estonia" },
  { iso2: "sz", country_name: "Eswatini" },
  { iso2: "et", country_name: "Ethiopia" },
  { iso2: "fj", country_name: "Fiji" },
  { iso2: "fi", country_name: "Finland" },
  { iso2: "fr", country_name: "France" },
  { iso2: "ga", country_name: "Gabon" },
  { iso2: "gm", country_name: "Gambia" },
  { iso2: "ge", country_name: "Georgia" },
  { iso2: "de", country_name: "Germany" },
  { iso2: "gh", country_name: "Ghana" },
  { iso2: "gr", country_name: "Greece" },
  { iso2: "gd", country_name: "Grenada" },
  { iso2: "gt", country_name: "Guatemala" },
  { iso2: "gn", country_name: "Guinea" },
  { iso2: "gw", country_name: "Guinea-Bissau" },
  { iso2: "gy", country_name: "Guyana" },
  { iso2: "ht", country_name: "Haiti" },
  { iso2: "hn", country_name: "Honduras" },
  { iso2: "hu", country_name: "Hungary" },
  { iso2: "is", country_name: "Iceland" },
  { iso2: "in", country_name: "India" },
  { iso2: "id", country_name: "Indonesia" },
  { iso2: "ir", country_name: "Iran" },
  { iso2: "iq", country_name: "Iraq" },
  { iso2: "ie", country_name: "Ireland" },
  { iso2: "il", country_name: "Israel" },
  { iso2: "it", country_name: "Italy" },
  { iso2: "jm", country_name: "Jamaica" },
  { iso2: "jp", country_name: "Japan" },
  { iso2: "jo", country_name: "Jordan" },
  { iso2: "kz", country_name: "Kazakhstan" },
  { iso2: "ke", country_name: "Kenya" },
  { iso2: "ki", country_name: "Kiribati" },
  { iso2: "kp", country_name: "North Korea" },
  { iso2: "kr", country_name: "South Korea" },
  { iso2: "kw", country_name: "Kuwait" },
  { iso2: "kg", country_name: "Kyrgyzstan" },
  { iso2: "la", country_name: "Laos" },
  { iso2: "lv", country_name: "Latvia" },
  { iso2: "lb", country_name: "Lebanon" },
  { iso2: "ls", country_name: "Lesotho" },
  { iso2: "lr", country_name: "Liberia" },
  { iso2: "ly", country_name: "Libya" },
  { iso2: "li", country_name: "Liechtenstein" },
  { iso2: "lt", country_name: "Lithuania" },
  { iso2: "lu", country_name: "Luxembourg" },
  { iso2: "mg", country_name: "Madagascar" },
  { iso2: "mw", country_name: "Malawi" },
  { iso2: "my", country_name: "Malaysia" },
  { iso2: "mv", country_name: "Maldives" },
  { iso2: "ml", country_name: "Mali" },
  { iso2: "mt", country_name: "Malta" },
  { iso2: "mh", country_name: "Marshall Islands" },
  { iso2: "mr", country_name: "Mauritania" },
  { iso2: "mu", country_name: "Mauritius" },
  { iso2: "mx", country_name: "Mexico" },
  { iso2: "fm", country_name: "Micronesia" },
  { iso2: "md", country_name: "Moldova" },
  { iso2: "mc", country_name: "Monaco" },
  { iso2: "mn", country_name: "Mongolia" },
  { iso2: "me", country_name: "Montenegro" },
  { iso2: "ma", country_name: "Morocco" },
  { iso2: "mz", country_name: "Mozambique" },
  { iso2: "mm", country_name: "Myanmar" },
  { iso2: "na", country_name: "Namibia" },
  { iso2: "nr", country_name: "Nauru" },
  { iso2: "np", country_name: "Nepal" },
  { iso2: "nl", country_name: "Netherlands" },
  { iso2: "nz", country_name: "New Zealand" },
  { iso2: "ni", country_name: "Nicaragua" },
  { iso2: "ne", country_name: "Niger" },
  { iso2: "ng", country_name: "Nigeria" },
  { iso2: "mk", country_name: "North Macedonia" },
  { iso2: "no", country_name: "Norway" },
  { iso2: "om", country_name: "Oman" },
  { iso2: "pk", country_name: "Pakistan" },
  { iso2: "pw", country_name: "Palau" },
  { iso2: "pa", country_name: "Panama" },
  { iso2: "pg", country_name: "Papua New Guinea" },
  { iso2: "py", country_name: "Paraguay" },
  { iso2: "pe", country_name: "Peru" },
  { iso2: "ph", country_name: "Philippines" },
  { iso2: "pl", country_name: "Poland" },
  { iso2: "pt", country_name: "Portugal" },
  { iso2: "qa", country_name: "Qatar" },
  { iso2: "ro", country_name: "Romania" },
  { iso2: "ru", country_name: "Russia" },
  { iso2: "rw", country_name: "Rwanda" },
  { iso2: "kn", country_name: "Saint Kitts and Nevis" },
  { iso2: "lc", country_name: "Saint Lucia" },
  { iso2: "vc", country_name: "Saint Vincent and the Grenadines" },
  { iso2: "ws", country_name: "Samoa" },
  { iso2: "sm", country_name: "San Marino" },
  { iso2: "st", country_name: "São Tomé and Príncipe" },
  { iso2: "sa", country_name: "Saudi Arabia" },
  { iso2: "sn", country_name: "Senegal" },
  { iso2: "rs", country_name: "Serbia" },
  { iso2: "sc", country_name: "Seychelles" },
  { iso2: "sl", country_name: "Sierra Leone" },
  { iso2: "sg", country_name: "Singapore" },
  { iso2: "sk", country_name: "Slovakia" },
  { iso2: "si", country_name: "Slovenia" },
  { iso2: "sb", country_name: "Solomon Islands" },
  { iso2: "so", country_name: "Somalia" },
  { iso2: "za", country_name: "South Africa" },
  { iso2: "ss", country_name: "South Sudan" },
  { iso2: "es", country_name: "Spain" },
  { iso2: "lk", country_name: "Sri Lanka" },
  { iso2: "sd", country_name: "Sudan" },
  { iso2: "sr", country_name: "Suriname" },
  { iso2: "se", country_name: "Sweden" },
  { iso2: "ch", country_name: "Switzerland" },
  { iso2: "sy", country_name: "Syria" },
  { iso2: "tj", country_name: "Tajikistan" },
  { iso2: "tz", country_name: "Tanzania" },
  { iso2: "th", country_name: "Thailand" },
  { iso2: "tl", country_name: "Timor-Leste" },
  { iso2: "tg", country_name: "Togo" },
  { iso2: "to", country_name: "Tonga" },
  { iso2: "tt", country_name: "Trinidad and Tobago" },
  { iso2: "tn", country_name: "Tunisia" },
  { iso2: "tr", country_name: "Turkey" },
  { iso2: "tm", country_name: "Turkmenistan" },
  { iso2: "tv", country_name: "Tuvalu" },
  { iso2: "ug", country_name: "Uganda" },
  { iso2: "ua", country_name: "Ukraine" },
  { iso2: "ae", country_name: "United Arab Emirates" },
  { iso2: "gb", country_name: "United Kingdom" },
  { iso2: "us", country_name: "United States" },
  { iso2: "uy", country_name: "Uruguay" },
  { iso2: "uz", country_name: "Uzbekistan" },
  { iso2: "vu", country_name: "Vanuatu" },
  { iso2: "va", country_name: "Vatican City" },
  { iso2: "ve", country_name: "Venezuela" },
  { iso2: "vn", country_name: "Vietnam" },
  { iso2: "ye", country_name: "Yemen" },
  { iso2: "zm", country_name: "Zambia" },
  { iso2: "zw", country_name: "Zimbabwe" },
] as const;

export type FlagData = (typeof UN_MEMBER_FLAGS)[number];
